language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_script:
  - echo $KEYSTORE | base64 -d > app/keystore.jks
deploy:
  provider: releases
  api_key:
    secure: PzL76hfcDs47dnfx3LH1p5zPJgktKY3lc8zIS1pX6+ow3yHpFI9CxCBF+GUBd9fMewy1fF9NKgWTCEov++HzikHv9TKg9NdZnZ08Vp41cSx0ThdiChVqKN8ZVZMURhNE0MPHg8Sv0fC1YEdkxZqdkwluS7vDH+Xo3ovbGl90nHANia06dfGOPj0MVOHY+hqUznja+2Yb3rdc8j0/2xo2PO1pvqY1Qhad29uBDA2GxK+fiKWlWMlRHdvjsIs9BJC+LdlcSLx3e69wF5Vj01t2XILsmq2tqi9S7Aqa6TgAGOfncPYgl+OGJZsmlxFaiJ3nh3N1WKaU/NTbMKbZTOyIh8WIj2R14+7qz05/Iaj66cigKFO0pXxE/uKAIwb5yNzV6xyNoBignWeyCwvSh4gplO9gfXFirEaWwPyef7vuyoagmyN8AIg8ea9rjvBkRgnZSFgdD0lZx1KgkFP9VKHtwKfN2VsXPUFAvtZrvpmWvmE2y9ZOZcGFbu29HVQhzt0J28QqMatp1Ghv6an6Lnw9yNau69TDj5x3qonpNyQHDj3hKUZ+IcdRK28fUb0YuX9TG8CfJDGzFVxw/7RAYNcvCSYA0KwgWJKkMLCEpt7kRsrCdXhR5NfJeR7V945h/JaQDvY0dEaKtTAiwMLGgum7g60Q3TuEuVsAErq/FRPZ9xg=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true
