name: android
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v1
        with:
          name: motionmate.apk
          path: app/build/outputs/apk/debug/app-debug.apk
